# Generated by Django 4.0.4 on 2022-04-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_title', models.CharField(max_length=40, verbose_name='Title')),
                ('link_descrip', models.CharField(max_length=200, verbose_name='Link Description')),
                ('link_url', models.URLField(verbose_name='Link URL')),
            ],
        ),
    ]
